import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "./components/header/NavigationBar";
import Footer from "./components/footer/Footer";
import { ToastProvider } from "./utils/context/toast/toastContext";
import ToastWrapper from "./utils/context/toast/ToastWrapper";
// here i would fetch if the user is signed in if they are

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-dark-blue text-primary-white font-primary antialiased`}
      >
        <ToastProvider>
          <ToastWrapper />
          <NavigationBar></NavigationBar>
          {children}
          <Footer />
        </ToastProvider>
      </body>
    </html>
  );
}
