import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "./components/header/NavigationBar";
// here i would fetch if the user is signed in if they are

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-dark-blue text-primary-white font-primary antialiased`}
      >
        <NavigationBar></NavigationBar>
        {children}
      </body>
    </html>
  );
}
